
#pragma once

#include <vector>
#include <string>

const std::vector<std::string> ZERO_3_DIRECTORY_LIST = {
    "bin/data/",
    "bin/data/tim2/",
    "bin/data/tim2/hint/",
    "bin/data/tim2/item/",
    "bin/data/tim2/file/",
    "bin/data/tim2/candle/",
    "bin/data/tim2/genzou/",
    "bin/data/tim2/memo/",
    "bin/data/tim2/event/",
    "bin/data/tim2/chapter/",
    "bin/data/tim2/snapshot/",
    "bin/data/tim2/album/",
    "bin/data/tim2/saveload/",
    "bin/data/tim2/gallery/",
    "bin/data/tim2/ghostlist/",
    "bin/data/tim2/jibaku/",
    "bin/data/tim2/lang_sel/",
    "bin/data/3ddata/room/model/",
    "bin/data/3ddata/room/",
    "bin/data/3ddata/room/data/",
    "bin/data/3ddata/room/obj_pack/",
    "bin/data/adpcm/",
    "bin/data/effect/",
    "bin/data/se/",
    "bin/data/event/",
    "bin/data/enemy/",
    "bin/data/npc/",
    "bin/data/scene/",
    "bin/data/movie/",
    "bin/data/msg/",
    "bin/data/3ddata/character/",
    "bin/data/3ddata/character/model/",
    "bin/data/3ddata/character/motion/",
    "bin/data/3ddata/character/shape/",
    "bin/data/3ddata/furniture/model/",
    "bin/data/3ddata/furniture/motion/",
    "bin/data/3ddata/accessory/model/",
    "bin/data/3ddata/fly/model/",
    "bin/data/3ddata/door/model/",
    "bin/data/3ddata/door/motion/",
    "bin/data/3ddata/object/model/",
    "bin/data/2ddata/b2d/",
    "bin/data/2ddata/clut/",
    "bin/data/2ddata/",
    "bin/data/2ddata/rec/",
    "bin/data/2ddata/map_snap/",
    "bin/data/3ddata/camera/",
    "bin/data/icon/",
    "bin/data/subtitle/",
    "bin/data/2ddata/tutorial/"
};

