
#pragma once

#include <vector>

const char *ZERO_2_DIRECTORY_LIST[ 54 ] = {
    "bin/data/tim/",
    "bin/data/",
    "bin/data/enemy/",
    "bin/data/se/",
    "bin/adpcm/",
    "bin/movie/",
    "bin/data/3ddata/room/pk2/",
    "bin/data/3ddata/room/pzb/",
    "bin/data/3ddata/room/mh/",
    "bin/data/3ddata/room/zld/",
    "bin/data/3ddata/furniture/",
    "bin/data/3ddata/door/",
    "bin/data/3ddata/item/",
    "bin/data/3ddata/camera/",
    "bin/data/3ddata/man/mdl/",
    "bin/data/3ddata/man/anm/",
    "bin/data/3ddata/man/anm/Auto_ghost/",
    "bin/data/event/",
    "bin/data/msg/",
    "bin/data/tim/title/",
    "bin/data/tim/hint/",
    "bin/data/damy/",
    "bin/data/scene/",
    "bin/data/tim/calibration/",
    "bin/data/tim/test2D/",
    "bin/data/tim/menu/",
    "bin/data/tim/chapter/",
    "bin/data/tim/item/",
    "bin/data/tim/bg/",
    "bin/data/tim/event2D/",
    "bin/data/tim/map/",
    "bin/data/tim/puzzle/",
    "bin/data/tim/loading/",
    "bin/data/tim/kusabi/",
    "bin/data/tim/savepoint/",
    "bin/data/tim/file/pocketbook/",
    "bin/data/tim/file/scrap/",
    "bin/data/tim/file/oldbook/",
    "bin/data/tim/file/map/",
    "bin/data/tim/file/photograph/",
    "bin/data/tim/snapshot/",
    "bin/data/tim/gameover/",
    "bin/data/icon/",
    "bin/data/tim/radio_crystal/",
    "bin/data/effect/",
    "bin/data/tim/ghost_list/",
    "bin/data/tim/album/",
    "bin/data/tim/setup/",
    "bin/data/tim/option/",
    "bin/data/tim/mission/",
    "bin/data/tim/gallery/",
    "bin/data/tim/lang_sl/",
    "bin/data/tim/clear/",
    "bin/data/subtitle/",
};

